# coding:utf-8
URL = ""
# Bot
TELEGRAM_KEYS = "850313928:AAHAfmlDrHzOvWw8G21oGSfAYh0xiwNyGpM"
WEBHOOKING = URL + "/"+TELEGRAM_KEYS

# DataBase
ISMYSQL = False
MYSQL_HOST = "localhost"
MYSQL_DATABASE = "rss"
MYSQL_USERNAME = "root"
MYSQL_PASSWORD = "root"
MYSQL_PORT = 3306
DB_PATH = "rss.db"
